# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/openbsd6"
  #config.vm.box = "OpenBSD-6.8"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  config.vm.synced_folder ".", "/home/vagrant", type: "rsync"

  config.vm.provider "virtualbox" do |vb|
     vb.gui =    false
     vb.memory = "2048"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    set -e

    ls

    export AUTOCONF_VERSION=2.69
    export AUTOMAKE_VERSION=1.16

    sudo pkg_add git automake-1.16.2

    git clone https://github.com/universal-ctags/ctags
    cd ctags
    ./autogen
    ./configure
    make
    file ctags
    make check
  SHELL
end
